# Generated by Django 5.1.1 on 2024-09-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=150, null=True)),
                ('contexto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.IntegerField()),
                ('quantidade_confirmada', models.IntegerField(null=True)),
                ('quantidade_recebida', models.IntegerField(null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('valor_entrega', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('flag_entrega_ok', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('comentario', models.CharField(max_length=500)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.CreateModel(
            name='PerdaTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=300)),
                ('cor', models.CharField(max_length=20)),
                ('flag_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
