# Generated by Django 5.1.1 on 2024-09-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoDePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50)),
                ('lojas', models.ManyToManyField(blank=True, null=True, related_name='sugestoes_de_pedido', to='lojas.lojas')),
            ],
        ),
        migrations.CreateModel(
            name='SugestaoDePedidoItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.grupoproduto')),
                ('sugestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_da_sugestao', to='estoque.sugestaodepedido')),
            ],
        ),
    ]
