# Generated by Django 5.1.1 on 2024-09-21 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('lojas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventarioformulario',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.formulario'),
        ),
        migrations.AddField(
            model_name='inventarioformulario',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='inventario.inventario'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventarioformulario'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_do_inventario', to='inventario.inventario'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.grupoproduto'),
        ),
        migrations.AddField(
            model_name='tipodecontagem',
            name='formularios',
            field=models.ManyToManyField(to='inventario.formulario'),
        ),
        migrations.AddField(
            model_name='tipodecontagem',
            name='lojas',
            field=models.ManyToManyField(blank=True, null=True, related_name='tipos_de_contagens', to='lojas.lojas'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_de_contagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipodecontagem'),
        ),
    ]
